// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4PUC4dVG4XSPL7-_F7s3AyRC3prtNHU',
    appId: '1:566431802905:web:1d4f8f4614cc3b77d16c88',
    messagingSenderId: '566431802905',
    projectId: 'fugi-project',
    authDomain: 'fugi-project.firebaseapp.com',
    storageBucket: 'fugi-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3f7ioMHLinfDJbDuYrE3so-V2VJfmqGA',
    appId: '1:566431802905:android:3f67fe1582a7761fd16c88',
    messagingSenderId: '566431802905',
    projectId: 'fugi-project',
    storageBucket: 'fugi-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOvWGu0syig_s38OTsJi798MDIriS-_Ng',
    appId: '1:566431802905:ios:387a39d09cff4a27d16c88',
    messagingSenderId: '566431802905',
    projectId: 'fugi-project',
    storageBucket: 'fugi-project.appspot.com',
    iosClientId: '566431802905-nirjppj18qp0f8tgfj81n1uiqt8bp7kn.apps.googleusercontent.com',
    iosBundleId: 'com.frdynurm.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOvWGu0syig_s38OTsJi798MDIriS-_Ng',
    appId: '1:566431802905:ios:387a39d09cff4a27d16c88',
    messagingSenderId: '566431802905',
    projectId: 'fugi-project',
    storageBucket: 'fugi-project.appspot.com',
    iosClientId: '566431802905-nirjppj18qp0f8tgfj81n1uiqt8bp7kn.apps.googleusercontent.com',
    iosBundleId: 'com.frdynurm.loginFirebase',
  );
}
